/* @bruin
name: bruin_shop_raw.marketing_funnel
type: bq.sql
connection: bruin-playground-arsalan
description: |
  Deterministic synthetic ecommerce acquisition funnel for a US apparel
  company. Rows are generated by date, channel, campaign, and city market, then
  used as the common source for fake ads, GA4, Klaviyo, and Shopify order facts.
  Paid social is calibrated so New York in May 2025 is roughly $30K spend,
  1M impressions, 2% CTR, 10% click-to-order conversion, and about 2K orders.
  Special campaign, outage, stockout, and product-defect events are injected
  deterministically for dashboard storytelling and anomaly testing.

depends:
  - bruin_shop_raw.us_markets
  - bruin_shop_raw.special_events

materialization:
  type: table
  strategy: create+replace

columns:
  - name: activity_date
    type: DATE
    description: Synthetic activity date from 2025-01-01 through 2026-06-05.
    primary_key: true
    nullable: false
  - name: channel
    type: VARCHAR
    description: Normalized channel used across marketing, GA4, and order attribution.
    primary_key: true
  - name: campaign_id
    type: VARCHAR
    description: Stable campaign identifier.
    primary_key: true
  - name: market_id
    type: INTEGER
    description: Synthetic US city-market identifier.
    primary_key: true
  - name: platform
    type: VARCHAR
    description: Source platform label such as Meta, Google, Klaviyo, organic, or direct.
  - name: source
    type: VARCHAR
    description: GA4-compatible source value.
  - name: medium
    type: VARCHAR
    description: GA4-compatible medium value.
  - name: campaign_name
    type: VARCHAR
    description: Campaign display name.
  - name: special_event_id
    type: VARCHAR
    description: Synthetic event identifier when the row belongs to an injected campaign or sitewide incident.
  - name: special_event_type
    type: VARCHAR
    description: Synthetic event type used for dashboard filtering.
  - name: special_event_name
    type: VARCHAR
    description: Human-readable synthetic event name.
  - name: event_phase
    type: VARCHAR
    description: Event phase such as launch_push, stockout_waste, outage, or recovery.
  - name: featured_product_id
    type: VARCHAR
    description: Product identifier featured by a synthetic campaign when applicable.
  - name: city
    type: VARCHAR
    description: US city market.
  - name: state_code
    type: VARCHAR
    description: Two-letter US state or district postal abbreviation.
  - name: state_name
    type: VARCHAR
    description: Full US state or district name.
  - name: region
    type: VARCHAR
    description: US region used for seasonal demand adjustments.
  - name: spend
    type: DOUBLE
    description: Daily marketing spend in USD. Zero for non-paid traffic.
  - name: impressions
    type: INTEGER
    description: Daily ad impressions, email recipients, or zero for unpaid non-email channels.
  - name: clicks
    type: INTEGER
    description: Daily ad/email clicks. Zero for organic and direct traffic.
  - name: sessions
    type: INTEGER
    description: Daily web sessions attributed to the channel and market.
  - name: new_users
    type: INTEGER
    description: Daily new users attributed to the channel and market.
  - name: engaged_sessions
    type: INTEGER
    description: Daily engaged sessions attributed to the channel and market.
  - name: conversions
    type: INTEGER
    description: Daily purchase conversions. Shopify orders are generated one-for-one from this field.
  - name: ctr
    type: DOUBLE
    description: Click-through rate for paid and email rows, expressed as a percentage.
  - name: click_to_order_rate
    type: DOUBLE
    description: Click-to-order or session-to-order conversion rate, expressed as a percentage.

@bruin */

WITH calendar AS (
    SELECT activity_date
    FROM UNNEST(GENERATE_DATE_ARRAY(DATE '2025-01-01', DATE '2026-06-05')) AS activity_date
),
channels AS (
    SELECT *
    FROM UNNEST([
        STRUCT('paid_ads' AS channel, 'Meta' AS platform, 'instagram' AS source, 'cpc' AS medium, 'meta_instagram_prospecting' AS campaign_id, 'Instagram Prospecting - Apparel' AS campaign_name, 90.00 AS spend_per_weight, 30.00 AS cpm_usd, 0.0200 AS paid_ctr, 0.1000 AS paid_click_to_order_rate, 0.00 AS sessions_per_weight, 0.0000 AS session_to_order_rate, 0.72 AS new_user_rate, 0.67 AS engagement_rate),
        STRUCT('paid_search' AS channel, 'Google Ads' AS platform, 'google' AS source, 'cpc' AS medium, 'google_search_nonbrand' AS campaign_id, 'Google Search - Nonbrand Apparel' AS campaign_name, 42.00 AS spend_per_weight, 38.00 AS cpm_usd, 0.0350 AS paid_ctr, 0.0700 AS paid_click_to_order_rate, 0.00 AS sessions_per_weight, 0.0000 AS session_to_order_rate, 0.58 AS new_user_rate, 0.72 AS engagement_rate),
        STRUCT('email' AS channel, 'Klaviyo' AS platform, 'klaviyo' AS source, 'email' AS medium, 'klaviyo_lifecycle' AS campaign_id, 'Klaviyo Lifecycle Offers' AS campaign_name, 0.00 AS spend_per_weight, 0.00 AS cpm_usd, 0.1050 AS paid_ctr, 0.0550 AS paid_click_to_order_rate, 25.00 AS sessions_per_weight, 0.0000 AS session_to_order_rate, 0.18 AS new_user_rate, 0.78 AS engagement_rate),
        STRUCT('organic_search' AS channel, 'Google Organic' AS platform, 'google' AS source, 'organic' AS medium, 'organic_search' AS campaign_id, 'Organic Search' AS campaign_name, 0.00 AS spend_per_weight, 0.00 AS cpm_usd, 0.0000 AS paid_ctr, 0.0000 AS paid_click_to_order_rate, 70.00 AS sessions_per_weight, 0.0240 AS session_to_order_rate, 0.44 AS new_user_rate, 0.63 AS engagement_rate),
        STRUCT('direct' AS channel, 'Direct' AS platform, '(direct)' AS source, '(none)' AS medium, 'direct_traffic' AS campaign_id, 'Direct Traffic' AS campaign_name, 0.00 AS spend_per_weight, 0.00 AS cpm_usd, 0.0000 AS paid_ctr, 0.0000 AS paid_click_to_order_rate, 45.00 AS sessions_per_weight, 0.0210 AS session_to_order_rate, 0.26 AS new_user_rate, 0.58 AS engagement_rate)
    ])
),
base AS (
    SELECT
        c.activity_date,
        ch.*,
        m.market_id,
        m.city,
        m.state_code,
        m.state_name,
        m.region,
        m.demand_weight,
        CASE
            WHEN ch.channel = 'paid_search'
                AND c.activity_date BETWEEN DATE '2026-01-12' AND DATE '2026-01-18'
                THEN 'google_search_ctr_failure'
            WHEN c.activity_date BETWEEN DATE '2026-02-04' AND DATE '2026-02-05'
                THEN 'website_outage_12h'
            WHEN ch.channel = 'paid_ads'
                AND c.activity_date BETWEEN DATE '2026-03-10' AND DATE '2026-03-21'
                THEN 'instagram_trail_shoe_stockout'
            WHEN ch.channel = 'paid_ads'
                AND c.activity_date BETWEEN DATE '2026-04-08' AND DATE '2026-04-14'
                THEN 'instagram_spring_outfit_win'
            WHEN ch.channel = 'paid_search'
                AND c.activity_date BETWEEN DATE '2026-05-11' AND DATE '2026-05-17'
                THEN 'google_memorial_day_win'
        END AS special_event_id,
        CASE
            WHEN c.activity_date = DATE '2026-02-04' THEN 'outage'
            WHEN c.activity_date = DATE '2026-02-05' THEN 'recovery'
            WHEN ch.channel = 'paid_ads'
                AND c.activity_date BETWEEN DATE '2026-03-10' AND DATE '2026-03-17'
                THEN 'launch_push'
            WHEN ch.channel = 'paid_ads'
                AND c.activity_date BETWEEN DATE '2026-03-18' AND DATE '2026-03-21'
                THEN 'stockout_waste'
            WHEN ch.channel IN ('paid_ads', 'paid_search') THEN 'campaign'
        END AS event_phase,
        CASE
            WHEN ch.channel = 'paid_ads'
                AND c.activity_date BETWEEN DATE '2026-03-10' AND DATE '2026-03-21'
                THEN 'prod_shoes_04'
        END AS featured_product_id,
        CASE EXTRACT(MONTH FROM c.activity_date)
            WHEN 1 THEN 0.72
            WHEN 2 THEN 0.78
            WHEN 3 THEN 0.88
            WHEN 4 THEN 0.94
            WHEN 5 THEN 1.02
            WHEN 6 THEN 1.08
            WHEN 7 THEN 1.05
            WHEN 8 THEN 1.12
            WHEN 9 THEN 1.00
            WHEN 10 THEN 1.12
            WHEN 11 THEN 1.20
            WHEN 12 THEN 1.25
        END AS month_factor,
        CASE EXTRACT(DAYOFWEEK FROM c.activity_date)
            WHEN 1 THEN 0.88
            WHEN 2 THEN 0.92
            WHEN 3 THEN 0.96
            WHEN 4 THEN 1.00
            WHEN 5 THEN 1.04
            WHEN 6 THEN 1.15
            WHEN 7 THEN 1.08
        END AS day_factor,
        CASE
            WHEN c.activity_date BETWEEN DATE '2025-11-27' AND DATE '2025-12-01' THEN 1.18
            WHEN c.activity_date BETWEEN DATE '2025-12-10' AND DATE '2025-12-20' THEN 1.08
            WHEN c.activity_date BETWEEN DATE '2026-05-22' AND DATE '2026-05-25' THEN 1.08
            WHEN c.activity_date BETWEEN DATE '2025-05-23' AND DATE '2025-05-26' THEN 1.08
            ELSE 1.00
        END AS holiday_factor,
        0.92 + ABS(MOD(FARM_FINGERPRINT(CONCAT(CAST(c.activity_date AS STRING), ch.channel, CAST(m.market_id AS STRING), 'volume')), 17)) / 100.0 AS volume_noise,
        0.96 + ABS(MOD(FARM_FINGERPRINT(CONCAT(CAST(c.activity_date AS STRING), ch.channel, CAST(m.market_id AS STRING), 'rate')), 9)) / 100.0 AS rate_noise
    FROM calendar c
    CROSS JOIN channels ch
    CROSS JOIN bruin_shop_raw.us_markets m
),
annotated AS (
    SELECT
        b.*,
        e.event_name AS special_event_name,
        e.event_type AS special_event_type,
        COALESCE(e.campaign_id, b.campaign_id) AS applied_campaign_id,
        CASE
            WHEN e.campaign_id IS NOT NULL THEN e.event_name
            ELSE b.campaign_name
        END AS applied_campaign_name
    FROM base b
    LEFT JOIN bruin_shop_raw.special_events e
        ON b.special_event_id = e.event_id
),
scaled AS (
    SELECT
        *,
        month_factor * day_factor * holiday_factor * volume_noise AS volume_factor,
        CASE
            WHEN special_event_id = 'google_search_ctr_failure' THEN 1.08
            WHEN special_event_id = 'instagram_trail_shoe_stockout' THEN 1.58
            WHEN special_event_id = 'instagram_spring_outfit_win' THEN 1.16
            WHEN special_event_id = 'google_memorial_day_win' THEN 1.12
            ELSE 1.00
        END AS spend_multiplier,
        CASE
            WHEN special_event_id = 'google_search_ctr_failure' THEN 1.08
            WHEN special_event_id = 'instagram_trail_shoe_stockout' THEN 1.42
            WHEN special_event_id = 'instagram_spring_outfit_win' THEN 1.14
            WHEN special_event_id = 'google_memorial_day_win' THEN 1.10
            ELSE 1.00
        END AS impression_multiplier,
        CASE
            WHEN special_event_id = 'google_search_ctr_failure' THEN 0.18
            WHEN special_event_id = 'instagram_trail_shoe_stockout' AND event_phase = 'launch_push' THEN 1.45
            WHEN special_event_id = 'instagram_trail_shoe_stockout' AND event_phase = 'stockout_waste' THEN 1.20
            WHEN special_event_id = 'instagram_spring_outfit_win' THEN 1.62
            WHEN special_event_id = 'google_memorial_day_win' THEN 1.50
            ELSE 1.00
        END AS ctr_multiplier,
        CASE
            WHEN special_event_id = 'google_search_ctr_failure' THEN 0.20
            WHEN special_event_id = 'website_outage_12h' AND event_phase = 'outage' THEN 0.42
            WHEN special_event_id = 'website_outage_12h' AND event_phase = 'recovery' THEN 1.18
            WHEN special_event_id = 'instagram_trail_shoe_stockout' AND event_phase = 'launch_push' THEN 1.55
            WHEN special_event_id = 'instagram_trail_shoe_stockout' AND event_phase = 'stockout_waste' THEN 0.01
            WHEN special_event_id = 'instagram_spring_outfit_win' THEN 1.36
            WHEN special_event_id = 'google_memorial_day_win' THEN 1.30
            ELSE 1.00
        END AS order_rate_multiplier,
        CASE
            WHEN special_event_id = 'website_outage_12h' AND event_phase = 'outage' THEN 0.52
            WHEN special_event_id = 'website_outage_12h' AND event_phase = 'recovery' THEN 1.12
            ELSE 1.00
        END AS session_multiplier
    FROM annotated
),
paid AS (
    SELECT
        *,
        ROUND(spend_per_weight * demand_weight * volume_factor * spend_multiplier, 2) AS paid_spend,
        CAST(ROUND(SAFE_DIVIDE(spend_per_weight * demand_weight * volume_factor * impression_multiplier * 1000, NULLIF(cpm_usd, 0))) AS INT64) AS paid_impressions
    FROM scaled
    WHERE channel IN ('paid_ads', 'paid_search')
),
paid_adjusted AS (
    SELECT
        *,
        CAST(ROUND(paid_impressions * paid_ctr * rate_noise * ctr_multiplier) AS INT64) AS paid_clicks
    FROM paid
),
paid_final AS (
    SELECT
        activity_date,
        channel,
        applied_campaign_id AS campaign_id,
        platform,
        source,
        medium,
        applied_campaign_name AS campaign_name,
        special_event_id,
        special_event_type,
        special_event_name,
        event_phase,
        featured_product_id,
        market_id,
        city,
        state_code,
        state_name,
        region,
        paid_spend AS spend,
        paid_impressions AS impressions,
        paid_clicks AS clicks,
        CAST(ROUND(paid_clicks * paid_click_to_order_rate * order_rate_multiplier) AS INT64) AS conversions,
        CAST(ROUND(paid_clicks * 1.03 * session_multiplier) AS INT64) AS sessions,
        new_user_rate,
        engagement_rate,
        paid_ctr * rate_noise * ctr_multiplier AS ctr_ratio,
        paid_click_to_order_rate * order_rate_multiplier AS conversion_ratio
    FROM paid_adjusted
),
email AS (
    SELECT
        activity_date,
        channel,
        applied_campaign_id AS campaign_id,
        platform,
        source,
        medium,
        applied_campaign_name AS campaign_name,
        special_event_id,
        special_event_type,
        special_event_name,
        event_phase,
        featured_product_id,
        market_id,
        city,
        state_code,
        state_name,
        region,
        CAST(0 AS NUMERIC) AS spend,
        CAST(ROUND(sessions_per_weight * demand_weight * volume_factor / NULLIF(paid_ctr, 0)) AS INT64) AS impressions,
        CAST(ROUND(sessions_per_weight * demand_weight * volume_factor) AS INT64) AS clicks,
        CAST(ROUND(sessions_per_weight * demand_weight * volume_factor * paid_click_to_order_rate * rate_noise * order_rate_multiplier) AS INT64) AS conversions,
        CAST(ROUND(sessions_per_weight * demand_weight * volume_factor * session_multiplier) AS INT64) AS sessions,
        new_user_rate,
        engagement_rate,
        paid_ctr AS ctr_ratio,
        paid_click_to_order_rate * rate_noise * order_rate_multiplier AS conversion_ratio
    FROM scaled
    WHERE channel = 'email'
),
unpaid AS (
    SELECT
        activity_date,
        channel,
        applied_campaign_id AS campaign_id,
        platform,
        source,
        medium,
        applied_campaign_name AS campaign_name,
        special_event_id,
        special_event_type,
        special_event_name,
        event_phase,
        featured_product_id,
        market_id,
        city,
        state_code,
        state_name,
        region,
        CAST(0 AS NUMERIC) AS spend,
        CAST(0 AS INT64) AS impressions,
        CAST(0 AS INT64) AS clicks,
        CAST(ROUND(sessions_per_weight * demand_weight * volume_factor * session_multiplier * session_to_order_rate * rate_noise * order_rate_multiplier) AS INT64) AS conversions,
        CAST(ROUND(sessions_per_weight * demand_weight * volume_factor * session_multiplier) AS INT64) AS sessions,
        new_user_rate,
        engagement_rate,
        CAST(NULL AS FLOAT64) AS ctr_ratio,
        session_to_order_rate * rate_noise * order_rate_multiplier AS conversion_ratio
    FROM scaled
    WHERE channel IN ('organic_search', 'direct')
),
combined AS (
    SELECT * FROM paid_final
    UNION ALL
    SELECT * FROM email
    UNION ALL
    SELECT * FROM unpaid
)

SELECT
    activity_date,
    channel,
    campaign_id,
    market_id,
    platform,
    source,
    medium,
    campaign_name,
    special_event_id,
    special_event_type,
    special_event_name,
    event_phase,
    featured_product_id,
    city,
    state_code,
    state_name,
    region,
    ROUND(CAST(spend AS NUMERIC), 2) AS spend,
    impressions,
    clicks,
    sessions,
    CAST(ROUND(sessions * new_user_rate) AS INT64) AS new_users,
    CAST(ROUND(sessions * engagement_rate) AS INT64) AS engaged_sessions,
    conversions,
    ROUND(ctr_ratio * 100, 2) AS ctr,
    ROUND(conversion_ratio * 100, 2) AS click_to_order_rate
FROM combined
WHERE sessions > 0
ORDER BY activity_date, channel, market_id
