"""@bruin

name: contoso_raw.customers
description: |
  Customer dimension table for Contoso Electronics - a comprehensive view of customer profiles
  across 8 countries (US, Canada, France, Germany, UK, Italy, Netherlands, Australia).

  This table supports Slowly Changing Dimension (SCD) Type 2 tracking with start/end date pairs
  allowing historical customer attribute changes to be preserved. Contains synthetic but realistic
  customer data generated by SQLBI's Contoso Data Generator V2.

  Key characteristics:
  - 105K customer records with full demographic and geographic profiles
  - Multi-national customer base spanning North America, Europe, and Australia
  - Complete address information with geocoded latitude/longitude coordinates
  - Personal details including age, occupation, employer, and vehicle ownership
  - All data is synthetic/generated - no real PII despite realistic appearance

  Typical usage patterns:
  - Customer segmentation and demographic analysis
  - Geographic market analysis and store catchment modeling
  - Joins with sales/orders data for customer lifetime value calculations
  - Marketing campaign targeting based on demographics or location

  Source: SQLBI Contoso Data Generator V2 (MIT license)
  Documentation: https://github.com/sql-bi/Contoso-Data-Generator-V2-Data
connection: bruin-playground-eu
instance: b1.medium
tags:
  - dimension_table
  - customer_data
  - retail
  - scd_type_2
  - multi_national
  - synthetic_pii
  - demographic_analysis

materialization:
  type: table
  strategy: create+replace
image: python:3.11


columns:
  - name: customer_key
    type: INTEGER
    description: |
      Surrogate key identifier for customer records. Used for SCD Type 2 tracking where
      a single customer may have multiple records with different start/end date ranges
      as their attributes change over time.
    primary_key: true
    checks:
      - name: not_null
  - name: geo_area_key
    type: INTEGER
    description: |
      Foreign key linking to geographic area dimension. Provides hierarchical geography
      mapping from specific locations to broader market regions for analytics.
    checks:
      - name: not_null
  - name: start_dt
    type: DATE
    description: |
      SCD Type 2 effective start date. Indicates when this version of the customer
      record became active. Used with end_dt to track historical changes to customer attributes.
    checks:
      - name: not_null
  - name: end_dt
    type: DATE
    description: |
      SCD Type 2 effective end date. Indicates when this version of the customer record
      was superseded. Future-dated for current active records.
  - name: continent
    type: VARCHAR
    description: |
      Continent where customer is located. Values: 'North America', 'Europe', 'Australia'.
      Useful for high-level geographic segmentation and regional business analysis.
    checks:
      - name: not_null
      - name: accepted_values
        value:
          - North America
          - Europe
          - Australia
  - name: gender
    type: VARCHAR
    description: |
      Customer gender for demographic segmentation. Values: 'male', 'female'.
      Used in marketing campaign targeting and product preference analysis.
    checks:
      - name: not_null
      - name: accepted_values
        value:
          - male
          - female
  - name: title
    type: VARCHAR
    description: |
      Name title or honorific (Mr., Mrs., Ms., Dr.). Reflects cultural naming conventions
      and can indicate customer preferences for formal communication.
  - name: given_name
    type: VARCHAR
    description: |
      Customer's first name. Approximately 9,300 unique values suggesting realistic
      name distribution. Used for personalized marketing and customer service.
  - name: middle_initial
    type: VARCHAR
    description: |
      Single character middle initial. Standard format for name disambiguation
      and formal addressing in customer communications.
  - name: surname
    type: VARCHAR
    description: |
      Customer's family/last name. Over 20,000 unique values indicating diverse
      name distribution across multiple countries and cultures.
  - name: street_address
    type: VARCHAR
    description: |
      Complete street address including house number and street name.
      High cardinality (~96K unique) suggests realistic address generation.
  - name: city
    type: VARCHAR
    description: |
      City name where customer resides. Over 34K unique cities across 8 countries,
      enabling local market analysis and store catchment area studies.
  - name: state
    type: VARCHAR
    description: |
      State, province, or administrative region abbreviation. Format varies by country
      (e.g., 'CA' for California, 'NSW' for New South Wales). Used for regional analysis.
  - name: state_full
    type: VARCHAR
    description: |
      Full name of state, province, or administrative region corresponding to the
      abbreviated state field. Provides human-readable geography for reporting.
  - name: zip_code
    type: VARCHAR
    description: |
      Postal code in local country format. String type accommodates different
      international postal code formats (5-digit US, postal codes with letters).
  - name: country
    type: VARCHAR
    description: |
      Two-letter ISO country code. Values: US, CA, FR, DE, GB, IT, NL, AU.
      Primary dimension for international business analysis and currency handling.
    checks:
      - name: not_null
      - name: accepted_values
        value:
          - US
          - CA
          - FR
          - DE
          - GB
          - IT
          - NL
          - AU
  - name: country_full
    type: VARCHAR
    description: |
      Full country name corresponding to the country code. Human-readable format
      for customer-facing reports and international market segmentation.
  - name: birthday
    type: DATE
    description: |
      Customer date of birth. Date range from 1935 to 2002 creating realistic age
      distribution. Used for age-based segmentation and lifecycle marketing.
    checks:
      - name: not_null
  - name: age
    type: INTEGER
    description: |
      Customer age in years, calculated from birthday. Average ~52 years with
      standard deviation of 19 years. Derived field for demographic analysis convenience.
    checks:
      - name: non_negative
      - name: max
        value: 150
  - name: occupation
    type: VARCHAR
    description: |
      Customer's profession or job title. Over 2,500 unique occupations providing
      rich data for professional/income-based segmentation and product targeting.
  - name: company
    type: VARCHAR
    description: |
      Customer's employer company name. About 1,000 unique companies with some
      empty values (105 records). May indicate self-employment or unemployment status.
  - name: vehicle
    type: VARCHAR
    description: |
      Customer's vehicle make and model. Nearly 12K unique combinations suggesting
      realistic automotive data. Useful for automotive-related product targeting.
  - name: latitude
    type: DOUBLE
    description: |
      Geographic latitude coordinate with 5 decimal places precision (~1 meter accuracy).
      Enables spatial analysis, distance calculations, and store catchment modeling.
    checks:
      - name: min
        value: -90
      - name: max
        value: 90
  - name: longitude
    type: DOUBLE
    description: |
      Geographic longitude coordinate with 5 decimal places precision (~1 meter accuracy).
      Combined with latitude for precise customer location mapping and analysis.
    checks:
      - name: min
        value: -180
      - name: max
        value: 180
  - name: extracted_at
    type: TIMESTAMP
    description: |
      Technical timestamp indicating when this data was loaded into the warehouse (UTC).
      Single value per batch indicating full table refresh pattern. Used for data lineage tracking.
    checks:
      - name: not_null

@bruin"""

import logging
import os
from datetime import datetime, timezone

import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _contoso_helpers import load_parquet

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(name)s - %(message)s",
)
logger = logging.getLogger(__name__)


def materialize():
    logger.info("Loading Contoso V2 customers data...")
    df = load_parquet("customers")
    df["extracted_at"] = datetime.now(timezone.utc)
    logger.info("Fetched %d rows", len(df))
    return df
